name: cyber-shield
version: 0.1.0
summary: NIDS
description: Network Intrusion Detection System

confinement: strict
base: core22
grade: stable

slots:
  dbus-cyber-shield: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.cyber_shield # adjust accordingly to your app name and

apps:
  cyber-shield:
    command: cyber_shield
    extensions: [] # gnome includes the libraries required by flutter
    plugs:
      - network
    slots:
      - dbus-cyber-shield
parts:
  cyber-shield:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
